[package]
name = "gosub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/*",
]

[dependencies]
config = { path = "crates/config", features = [] }
net = { path = "crates/net" }
